### ISSUE TITLE
Book update TODO-List

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py-book#366]
- [ ] 1) describe `{{=ASSIGNJS(js_var = python_var)}}`

- [ ] 2) new syntax to store .table files in DB itself instead of in the filesystem (works with any DB)

```python 
    from gluon import DAL, Field

    from gluon.dal import InDBMigrator

    db = DAL(uri, adapter_args=dict(migrator=InDBMigrator))
``` 

- [ ] 3) new syntax to connect to MySQL and Potgresql on GAE

Follow instructions https://cloud.google.com/appengine/docs/flexible/python/using-cloud-sql then use DAL//web2py URI:

```python 
"google:MySQLdb://username:password@/dbname?unix_socket=/cloudsql/projectname:dbzone:dbinstancename"

"google:psycopg2://username:password@/dbname?unix_socket=/cloudsql/projectname:dbzone:dbinstancename"
``` 

In this case the `adapter_args=dict(migrator=InDBMigrator))` is the default behavior. 

- [ ] 4) If you need to select lots of data and you do not want web2py to parse it into object but get the raw data as returned by the DB as a list of tuples:

```python 
rows = db(query).select(processor=lambda *a,**b: a[0])
``` 

- [ ] 5. the `ANY_OF` validator also needs to be documented

**Comment by wish7code** [comment]
- [ ] 6.Describe placeholder syntax for executesql
(http://www.web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#executesql)

**Comment by BuhtigithuB** [comment]
@wish7code, I think you point 6 has been fullfill since then : 

> placeholders is an optional sequence of values to be substituted in or, if supported by the DB driver, a dictionary with keys matching named placeholders in your SQL.

Can you confirm?

Thanks

**Comment by wish7code** [comment]
@BuhtigithuB Documentation has improved indeed, I remember placeholders being not mentioned at all. Still I find below 2010 mailing list explanation much more clear than the book, especially  @Richard_Galka answer back then, see
  
https://groups.google.com/forum/#!topic/web2py/a7p800sqdYg

Highly appreciate your efforts to make web2py documentation better!

**Comment by BuhtigithuB** [comment]
Can you extract the information and send a PR?

Thanks
